"""add flower and flower_image

Revision ID: 1b2f02fb3899
Revises: 027ba4909d08
Create Date: 2026-01-21 03:49:42.039906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2f02fb3899'
down_revision: Union[str, Sequence[str], None] = '027ba4909d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flower_id'), 'flower', ['id'], unique=False)
    op.create_table('flower_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flower_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flower_id'], ['flower.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flower_image_id'), 'flower_image', ['id'], unique=False)
    op.create_index(op.f('ix_flower_image_sort_order'), 'flower_image', ['sort_order'], unique=False)
    op.drop_constraint(op.f('refresh_token_token_hash_key'), 'refresh_token', type_='unique')
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token')
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_token_id'), 'refresh_token', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token')
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('refresh_token_token_hash_key'), 'refresh_token', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_flower_image_sort_order'), table_name='flower_image')
    op.drop_index(op.f('ix_flower_image_id'), table_name='flower_image')
    op.drop_table('flower_image')
    op.drop_index(op.f('ix_flower_id'), table_name='flower')
    op.drop_table('flower')
    # ### end Alembic commands ###
