"""add image_id fk to category and advice

Revision ID: 0afa0078220c
Revises: 1c1ad97aac86
Create Date: 2026-02-15 19:12:11.911796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0afa0078220c'
down_revision: Union[str, Sequence[str], None] = '1c1ad97aac86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.create_index(op.f('ix_product_images_image_id'), 'product_images', ['image_id'], unique=False)
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_images_sort_order'), 'product_images', ['sort_order'], unique=False)
    op.drop_index(op.f('ix_product_image_id'), table_name='product_image')
    op.drop_index(op.f('ix_product_image_product_id'), table_name='product_image')
    op.drop_index(op.f('ix_product_image_sort_order'), table_name='product_image')
    op.drop_table('product_image')
    op.add_column('advices', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_advices_image_id'), 'advices', ['image_id'], unique=False)
    op.create_foreign_key(None, 'advices', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    op.drop_column('advices', 'image_url')
    op.add_column('banner', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_banner_image_id'), 'banner', ['image_id'], unique=False)
    op.create_foreign_key(None, 'banner', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    op.drop_column('banner', 'image_url')
    op.add_column('category', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_category_image_id'), 'category', ['image_id'], unique=False)
    op.create_foreign_key(None, 'category', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    op.drop_column('category', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_index(op.f('ix_category_image_id'), table_name='category')
    op.drop_column('category', 'image_id')
    op.add_column('banner', sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'banner', type_='foreignkey')
    op.drop_index(op.f('ix_banner_image_id'), table_name='banner')
    op.drop_column('banner', 'image_id')
    op.add_column('advices', sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'advices', type_='foreignkey')
    op.drop_index(op.f('ix_advices_image_id'), table_name='advices')
    op.drop_column('advices', 'image_id')
    op.create_table('product_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('product_image_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_image_pkey'))
    )
    op.create_index(op.f('ix_product_image_sort_order'), 'product_image', ['sort_order'], unique=False)
    op.create_index(op.f('ix_product_image_product_id'), 'product_image', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_image_id'), 'product_image', ['id'], unique=False)
    op.drop_index(op.f('ix_product_images_sort_order'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_image_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    # ### end Alembic commands ###
