"""image_library_m2m

Revision ID: 1a91e4220608
Revises: 281c3ac3d0d5
Create Date: 2026-02-13 14:41:48.923073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a91e4220608"
down_revision: Union[str, Sequence[str], None] = "281c3ac3d0d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_image_id"), "image", ["id"], unique=False)
    op.create_table(
        "product_image_link",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["image_id"], ["image.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("product_id", "image_id"),
    )

    # Перенос данных из product_image в image
    op.execute("""
        INSERT INTO image (id, url, created_at)
        SELECT id, url, CURRENT_TIMESTAMP FROM product_image
    """)

    # Перенос связей в product_image_link
    op.execute("""
        INSERT INTO product_image_link (product_id, image_id, sort_order)
        SELECT product_id, id, sort_order FROM product_image
    """)

    # Синхронизация sequence для image.id
    op.execute("""
        SELECT setval('image_id_seq', (SELECT COALESCE(MAX(id), 0) FROM image) + 1, false)
    """)

    op.drop_index(op.f("ix_product_image_id"), table_name="product_image")
    op.drop_index(op.f("ix_product_image_product_id"), table_name="product_image")
    op.drop_index(op.f("ix_product_image_sort_order"), table_name="product_image")
    op.drop_table("product_image")
    op.alter_column("banner", "title", existing_type=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("banner", "title", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.create_table(
        "product_image",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column("sort_order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("product_image_product_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("product_image_pkey")),
    )

    # Восстановление данных в product_image из image + product_image_link
    op.execute("""
        INSERT INTO product_image (id, product_id, url, sort_order)
        SELECT i.id, pil.product_id, i.url, pil.sort_order
        FROM image i
        JOIN product_image_link pil ON i.id = pil.image_id
    """)

    op.create_index(op.f("ix_product_image_sort_order"), "product_image", ["sort_order"], unique=False)
    op.create_index(op.f("ix_product_image_product_id"), "product_image", ["product_id"], unique=False)
    op.create_index(op.f("ix_product_image_id"), "product_image", ["id"], unique=False)
    op.drop_table("product_image_link")
    op.drop_index(op.f("ix_image_id"), table_name="image")
    op.drop_table("image")
    # ### end Alembic commands ###
