"""add cartitem table_args

Revision ID: 27a28e81ca59
Revises: d8e7db8d5268
Create Date: 2026-01-22 03:33:43.981913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a28e81ca59'
down_revision: Union[str, Sequence[str], None] = 'd8e7db8d5268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cart_flower', 'cart_item', ['cart_id', 'flower_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cart_flower', 'cart_item', type_='unique')
    # ### end Alembic commands ###
