"""add payment fields to order

Revision ID: 27bd76c8910d
Revises: 82bf6b9dafdf
Create Date: 2026-01-29 09:23:22.601803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27bd76c8910d'
down_revision: Union[str, Sequence[str], None] = '82bf6b9dafdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('payment_id', sa.String(), nullable=True))
    op.add_column('order', sa.Column('idempotency_key', sa.UUID(), nullable=False))
    op.add_column('order', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('order', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('order_user_id_key'), 'order', type_='unique')
    op.create_unique_constraint(None, 'order', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='unique')
    op.create_unique_constraint(op.f('order_user_id_key'), 'order', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('order', 'paid_at')
    op.drop_column('order', 'expires_at')
    op.drop_column('order', 'idempotency_key')
    op.drop_column('order', 'payment_id')
    # ### end Alembic commands ###
