"""add sort_order to product

Revision ID: 281c3ac3d0d5
Revises: 3b01e7d74ac0
Create Date: 2026-02-11 14:41:09.518861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281c3ac3d0d5'
down_revision: Union[str, Sequence[str], None] = '3b01e7d74ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('delivery', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('product', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_product_sort_order'), 'product', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_sort_order'), table_name='product')
    op.drop_column('product', 'sort_order')
    op.drop_column('delivery', 'updated_at')
    op.drop_column('delivery', 'created_at')
    # ### end Alembic commands ###
