"""add_banner_description

Revision ID: 3b01e7d74ac0
Revises: 525d0da0862b
Create Date: 2026-02-08 13:07:04.216727

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b01e7d74ac0"
down_revision: Union[str, Sequence[str], None] = "525d0da0862b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("banner", sa.Column("description", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("banner", "description")
    # ### end Alembic commands ###
