"""add category

Revision ID: 3eea613dce32
Revises: f3abec54d0b4
Create Date: 2026-01-31 04:31:06.196447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eea613dce32'
down_revision: Union[str, Sequence[str], None] = 'f3abec54d0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=True)
    op.create_index(op.f('ix_category_sort_order'), 'category', ['sort_order'], unique=False)
    op.create_table('product_category',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    # Создаём enum тип сначала
    producttype = sa.Enum('FLOWER', 'GIFT', name='producttype')
    producttype.create(op.get_bind())

    # Добавляем колонку с дефолтным значением, потом убираем дефолт
    op.add_column('product', sa.Column('type', producttype, nullable=True))
    op.execute("UPDATE product SET type = 'FLOWER' WHERE type IS NULL")
    op.alter_column('product', 'type', nullable=False)

    op.alter_column('product', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_column('product', 'type')
    # Удаляем enum тип
    op.execute('DROP TYPE IF EXISTS producttype')
    op.drop_table('product_category')
    op.drop_index(op.f('ix_category_sort_order'), table_name='category')
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
