"""add link to advice

Revision ID: 4630456bfa2d
Revises: 4c4ed2c6db7f
Create Date: 2026-02-15 23:16:34.213069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4630456bfa2d'
down_revision: Union[str, Sequence[str], None] = '4c4ed2c6db7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advices', sa.Column('link', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advices', 'link')
    # ### end Alembic commands ###
