"""add link to banner

Revision ID: 4c4ed2c6db7f
Revises: 0afa0078220c
Create Date: 2026-02-15 23:00:21.249014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4ed2c6db7f'
down_revision: Union[str, Sequence[str], None] = '0afa0078220c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advices', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advices', sa.Column('link', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
