"""create refresh_token

Revision ID: 50c646e67ab3
Revises: 49d3ab7c5a08
Create Date: 2026-01-19 05:20:12.446445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c646e67ab3'
down_revision: Union[str, Sequence[str], None] = '49d3ab7c5a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column("user", "hash", new_column_name="password_hash")
    op.create_unique_constraint(None, "user", ["email"])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.alter_column("user", "password_hash", new_column_name="hash")
    # ### end Alembic commands ###
