"""add_product_fields_flower_banner

Revision ID: 525d0da0862b
Revises: e431a9fdffed
Create Date: 2026-02-06 13:25:36.539428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "525d0da0862b"
down_revision: Union[str, Sequence[str], None] = "e431a9fdffed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "banner",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("image_url", sa.String(length=512), nullable=True),
        sa.Column("link", sa.String(length=512), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_banner_id"), "banner", ["id"], unique=False)
    op.create_index(op.f("ix_banner_is_active"), "banner", ["is_active"], unique=False)
    op.create_index(op.f("ix_banner_sort_order"), "banner", ["sort_order"], unique=False)
    op.create_table(
        "flower",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_flower_id"), "flower", ["id"], unique=False)
    op.create_table(
        "bouquet_composition",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("flower_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["flower_id"], ["flower.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("product_id", "flower_id"),
    )
    op.drop_constraint(op.f("delivery_order_id_key"), "delivery", type_="unique")
    op.create_index(op.f("ix_delivery_order_id"), "delivery", ["order_id"], unique=True)
    op.create_index(op.f("ix_favourite_product_id"), "favourite", ["product_id"], unique=False)
    op.create_index(op.f("ix_order_user_id"), "order", ["user_id"], unique=False)
    op.alter_column(
        "pickup_point",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "pickup_point",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.add_column("product", sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")))
    op.add_column("product", sa.Column("in_stock", sa.Boolean(), nullable=False, server_default=sa.text("true")))
    op.create_index(op.f("ix_product_in_stock"), "product", ["in_stock"], unique=False)
    op.create_index(op.f("ix_product_is_active"), "product", ["is_active"], unique=False)
    op.create_index(op.f("ix_product_type"), "product", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_type"), table_name="product")
    op.drop_index(op.f("ix_product_is_active"), table_name="product")
    op.drop_index(op.f("ix_product_in_stock"), table_name="product")
    op.drop_column("product", "in_stock")
    op.drop_column("product", "is_active")
    op.alter_column(
        "pickup_point",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "pickup_point",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_order_user_id"), table_name="order")
    op.drop_index(op.f("ix_favourite_product_id"), table_name="favourite")
    op.drop_index(op.f("ix_delivery_order_id"), table_name="delivery")
    op.create_unique_constraint(
        op.f("delivery_order_id_key"), "delivery", ["order_id"], postgresql_nulls_not_distinct=False
    )
    op.drop_table("bouquet_composition")
    op.drop_index(op.f("ix_flower_id"), table_name="flower")
    op.drop_table("flower")
    op.drop_index(op.f("ix_banner_sort_order"), table_name="banner")
    op.drop_index(op.f("ix_banner_is_active"), table_name="banner")
    op.drop_index(op.f("ix_banner_id"), table_name="banner")
    op.drop_table("banner")
    # ### end Alembic commands ###
