"""Add pickup points

Revision ID: e431a9fdffed
Revises: 3eea613dce32
Create Date: 2026-02-01 21:40:38.484472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e431a9fdffed'
down_revision: Union[str, Sequence[str], None] = '3eea613dce32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickup_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('working_hours', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_point_id'), 'pickup_point', ['id'], unique=False)
    op.create_index(op.f('ix_pickup_point_sort_order'), 'pickup_point', ['sort_order'], unique=False)
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('discount_type', sa.Enum('PRODUCT', 'CATEGORY', name='discounttype'), nullable=False),
    sa.Column('percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('new_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(percentage IS NOT NULL) != (new_price IS NOT NULL)', name='ck_discount_one_value'),
    sa.CheckConstraint('(product_id IS NOT NULL) != (category_id IS NOT NULL)', name='ck_discount_one_target'),
    sa.CheckConstraint('category_id IS NULL OR new_price IS NULL', name='ck_category_no_new_price'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_category_id'), 'discount', ['category_id'], unique=False)
    op.create_index(op.f('ix_discount_id'), 'discount', ['id'], unique=False)
    op.create_index(op.f('ix_discount_product_id'), 'discount', ['product_id'], unique=False)
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_user_product')
    )
    op.create_index(op.f('ix_favourite_id'), 'favourite', ['id'], unique=False)
    op.create_index(op.f('ix_favourite_user_id'), 'favourite', ['user_id'], unique=False)
    op.create_index(op.f('ix_cart_item_cart_id'), 'cart_item', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_item_product_id'), 'cart_item', ['product_id'], unique=False)
    op.add_column('order', sa.Column('pickup_point_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_order_payment_id'), 'order', ['payment_id'], unique=True)
    op.create_foreign_key(None, 'order', 'pickup_point', ['pickup_point_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_item_product_id'), 'order_item', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_image_product_id'), 'product_image', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_image_product_id'), table_name='product_image')
    op.drop_index(op.f('ix_order_item_product_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_index(op.f('ix_order_payment_id'), table_name='order')
    op.drop_column('order', 'pickup_point_id')
    op.drop_index(op.f('ix_cart_item_product_id'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_cart_id'), table_name='cart_item')
    op.drop_index(op.f('ix_favourite_user_id'), table_name='favourite')
    op.drop_index(op.f('ix_favourite_id'), table_name='favourite')
    op.drop_table('favourite')
    op.drop_index(op.f('ix_discount_product_id'), table_name='discount')
    op.drop_index(op.f('ix_discount_id'), table_name='discount')
    op.drop_index(op.f('ix_discount_category_id'), table_name='discount')
    op.drop_table('discount')
    op.drop_index(op.f('ix_pickup_point_sort_order'), table_name='pickup_point')
    op.drop_index(op.f('ix_pickup_point_id'), table_name='pickup_point')
    op.drop_table('pickup_point')
    # ### end Alembic commands ###
